FROM nginx:latest

# Copy Nginx configuration file
COPY default.conf /etc/nginx/conf.d/default.conf

# Copy index.html to the Nginx web root
COPY index.html /usr/share/nginx/html.i/index.html

# Expose port 80
EXPOSE 80
