replicaCount: 1

image:
  repository: rajeshkrish/helmwebapp
  tag: latest
  pullPolicy: Always

service:
  name: helmwebapp
  type: LoadBalancer
  port: 80

ingress:
  enabled: false
  name: ""
  path: /
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: []

