name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -f flaskapp/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/flaskapp:latest flaskapp
        docker build -f nginx/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest nginx

    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/flaskapp:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Kubernetes using Helm
      run: |
        export KUBECONFIG=~/.kube/config
        helm upgrade --install helmwebapp ./helmwebapp --namespace default

    - name: Run integration tests
      run: |
        kubectl port-forward svc/helmwebapp 8080:80 &
        sleep 5
        pytest tests/test_flask_integration.py

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.1.1
      with:
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        message: "Deployment of helmwebapp on ${K8S_CLUSTER_NAME} completed successfully."
