name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

  docker-build:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker images
      run: |
        docker build -f flaskapp/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/flaskapp:latest .
        docker build -f nginx/Dockerfile -t ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest .

    - name: Push Docker images
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/flaskapp:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.15.4'  # Update to your required Helm version

    - name: Lint Helm Chart
      run: helm lint ./helmwebapp

    - name: Deploy to Kubernetes using Helm
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}  # Ensure this secret contains the base64 encoded kubeconfig
      run: |
        helm upgrade --install helmwebapp ./helmwebapp --namespace default

    - name: Run integration tests
      run: |
        kubectl port-forward svc/helmwebapp 8080:80 &
        sleep 5
        pytest tests/test_flask_integration.py  # Ensure this file exists and is properly configured

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2.1.1
      with:
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        message: "Deployment of helmwebapp on Kubernetes completed successfully."

